apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prisma
  namespace: prod
  labels:
    app: prisma
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: frontend
  template:
    metadata:
      name: frontend-prisma
      labels:
        app: prisma
        tier: frontend
    spec:
      containers:
        - name: frontend-prisma
          image: jensdl/frontend:prod.v22.11.21-18h41m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prisma-service
  namespace: prod
  labels:
    app: prisma
    tier: frontend
spec:
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 80
  selector:
     app: prisma
     tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: prisma.orcraft.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-prisma-service
            port:
              number: 4200
  tls:
  - hosts:
    - prisma.orcraft.net
    secretName: prod.prisma-tls