apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prisma
  namespace: prod
  labels:
    app: prisma
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: frontend
  template:
    metadata:
      name: frontend-prisma
      labels:
        app: prisma
        tier: frontend
    spec:
      containers:
        - name: frontend-prisma
          image: jensdl/frontend:prod.v22.11.21-18h41m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
