---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prisma
  namespace: dev
  labels:
    app: prisma
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: frontend
  template:
    metadata:
      name: frontend-prisma
      labels:
        app: prisma
        tier: frontend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: frontend-prisma
          image: jensdl/frontend:dev.v22.12.16-12h45m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: smb-devfe
              mountPath: "/usr/share/nginx/html/assets"
              readOnly: false
      volumes:
        - name: smb-devfe
          persistentVolumeClaim:
            claimName: pvc-smb-devfe
