---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-devfe
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: dev_frontend_smb # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//10.128.12.8/devfrontend"
    nodeStageSecretRef:
      name: smbcreds-devfe
      namespace: dev
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-devfe
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: smb-devfe
  storageClassName: smb
