apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prisma
  namespace: dev
  labels:
    app: prisma
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: frontend
  template:
    metadata:
      name: frontend-prisma
      labels:
        app: prisma
        tier: frontend
    spec:
      containers:
        - name: frontend-prisma
          image: jensdl/frontend:dev.v22.11.25-14h46m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prisma-service
  namespace: dev
  labels:
    app: prisma
    tier: frontend
spec:
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
  selector:
    app: prisma
    tier: frontend
  template:
    spec:
      containers:
        - image: jensdl/frontend:dev.v22.11.25-14h46m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: dev-redirect@kubernetescrd
spec:
  rules:
    - host: dev.prisma.orcraft.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-prisma-service
                port:
                  number: 4200
  tls:
  - hosts:
    - dev.prisma.orcraft.net
    secretName: dev.prisma-tls
